# Generated by Django 6.0.5 on 2026-06-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(default='Wear Your', max_length=100)),
                ('title_line2', models.CharField(default='Inner', max_length=100)),
                ('title_line3', models.CharField(default='Radiance', max_length=100)),
                ('eyebrow_text', models.CharField(default='New Collection 2025', max_length=100)),
                ('description', models.TextField(default='Exquisite handcrafted artificial jewelry — where timeless elegance meets contemporary artistry. Crafted for the discerning modern woman.')),
                ('primary_button_text', models.CharField(default='Shop Collection', max_length=50)),
                ('primary_button_link', models.CharField(default='/products/', max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, default='New Arrivals', max_length=50)),
                ('secondary_button_link', models.CharField(blank=True, default='/products/?filter=new', max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('stat1_value', models.CharField(default='50K+', max_length=20)),
                ('stat1_label', models.CharField(default='Happy Customers', max_length=50)),
                ('stat2_value', models.CharField(default='2K+', max_length=20)),
                ('stat2_label', models.CharField(default='Designs', max_length=50)),
                ('stat3_value', models.CharField(default='4.9★', max_length=20)),
                ('stat3_label', models.CharField(default='Rating', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rosella', max_length=100)),
                ('tagline', models.CharField(default='Luxury Jewels', max_length=200)),
                ('announcement_bar_text', models.CharField(default='✦ Free Shipping on Orders Over ₹999 | Use Code LUXURY15 for 15% Off ✦', max_length=300)),
                ('offer_title', models.CharField(blank=True, default='Up to 40% Off', max_length=200)),
                ('offer_subtitle', models.CharField(blank=True, default='On Bridal Collections', max_length=200)),
                ('offer_description', models.TextField(blank=True, default='Use code BRIDE40 at checkout. Limited period offer only.')),
                ('offer_code', models.CharField(blank=True, default='BRIDE40', max_length=20)),
                ('offer_hours', models.CharField(default='11', max_length=5)),
                ('offer_mins', models.CharField(default='47', max_length=5)),
                ('offer_secs', models.CharField(default='32', max_length=5)),
                ('instagram_handle', models.CharField(default='@rosellalujoyjewels', max_length=100)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=999, max_digits=10)),
                ('footer_description', models.TextField(blank=True, default='Handcrafted artificial jewelry that celebrates your elegance. Premium designs, affordable luxury.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_initials', models.CharField(max_length=5)),
                ('rating', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
